DROP TABLE IF EXISTS movie_director;
DROP TABLE IF EXISTS movie_writer;
DROP TABLE IF EXISTS movie_actor;
DROP TABLE IF EXISTS movie_area;
DROP TABLE IF EXISTS movie_type;
DROP TABLE IF EXISTS user_premovies;

DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS admin_users;

DROP TABLE IF EXISTS movies;

DROP TABLE IF EXISTS directors;
DROP TABLE IF EXISTS writers;
DROP TABLE IF EXISTS actors;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS areas;
